/**
 * GENERATED FILE — do not edit.
 * Produced by scripts/build-migrations.mjs from ./migrations/*.sql
 */

export interface Migration {
  readonly name: string;
  readonly statements: readonly string[];
}

export const MIGRATIONS: readonly Migration[] = [
  {
    "name": "0000_needy_oracle.sql",
    "statements": [
      "CREATE TABLE `fasting_sessions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`protocol` text NOT NULL,\n\t`started_at` text NOT NULL,\n\t`ended_at` text,\n\t`target_hours` real NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`deleted_at` text,\n\t`synced_at` text,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `fasting_sessions_user_started_idx` ON `fasting_sessions` (`user_id`,`started_at`);",
      "CREATE TABLE `food_items` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`brand` text,\n\t`barcode` text,\n\t`source` text NOT NULL,\n\t`source_ref` text,\n\t`confidence` real DEFAULT 1 NOT NULL,\n\t`verified` integer DEFAULT false NOT NULL,\n\t`user_submitted` integer DEFAULT false NOT NULL,\n\t`nutrients` text NOT NULL,\n\t`energy_kcal` real,\n\t`protein_g` real,\n\t`carbs_g` real,\n\t`fat_g` real,\n\t`fiber_g` real,\n\t`sugar_g` real,\n\t`sat_fat_g` real,\n\t`sodium_mg` real,\n\t`allergens` text DEFAULT '[]' NOT NULL,\n\t`cached_at` text,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`deleted_at` text,\n\t`synced_at` text\n);",
      "CREATE INDEX `food_items_barcode_idx` ON `food_items` (`barcode`);",
      "CREATE INDEX `food_items_name_idx` ON `food_items` (`name`);",
      "CREATE TABLE `food_portions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`food_item_id` text NOT NULL,\n\t`label` text NOT NULL,\n\t`grams` real NOT NULL,\n\t`is_default` integer DEFAULT false NOT NULL,\n\tFOREIGN KEY (`food_item_id`) REFERENCES `food_items`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `food_portions_food_idx` ON `food_portions` (`food_item_id`);",
      "CREATE TABLE `journal_entries` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`logged_at` text NOT NULL,\n\t`local_date` text NOT NULL,\n\t`meal_slot` text NOT NULL,\n\t`log_method` text NOT NULL,\n\t`note` text,\n\t`photo_uri` text,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`deleted_at` text,\n\t`synced_at` text,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `journal_entries_user_date_idx` ON `journal_entries` (`user_id`,`local_date`);",
      "CREATE TABLE `journal_entry_items` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`entry_id` text NOT NULL,\n\t`food_item_id` text,\n\t`recipe_id` text,\n\t`display_name` text NOT NULL,\n\t`grams` real NOT NULL,\n\t`portion_label` text,\n\t`portion_count` real,\n\t`nutrients` text NOT NULL,\n\t`energy_kcal` real,\n\t`protein_g` real,\n\t`carbs_g` real,\n\t`fat_g` real,\n\t`fiber_g` real,\n\t`sugar_g` real,\n\t`sat_fat_g` real,\n\t`sodium_mg` real,\n\t`confidence` real DEFAULT 1 NOT NULL,\n\t`source` text NOT NULL,\n\t`sort_order` integer DEFAULT 0 NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`deleted_at` text,\n\t`synced_at` text,\n\tFOREIGN KEY (`entry_id`) REFERENCES `journal_entries`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`food_item_id`) REFERENCES `food_items`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`recipe_id`) REFERENCES `recipes`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `journal_entry_items_entry_idx` ON `journal_entry_items` (`entry_id`);",
      "CREATE TABLE `meal_plan_slots` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`plan_id` text NOT NULL,\n\t`local_date` text NOT NULL,\n\t`meal_slot` text NOT NULL,\n\t`recipe_id` text,\n\t`servings` real DEFAULT 1 NOT NULL,\n\t`locked` integer DEFAULT false NOT NULL,\n\t`leftover_of_slot_id` text,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`deleted_at` text,\n\t`synced_at` text,\n\tFOREIGN KEY (`plan_id`) REFERENCES `meal_plans`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`recipe_id`) REFERENCES `recipes`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `meal_plan_slots_plan_idx` ON `meal_plan_slots` (`plan_id`,`local_date`);",
      "CREATE TABLE `meal_plans` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`week_start_date` text NOT NULL,\n\t`generated_at` text,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`deleted_at` text,\n\t`synced_at` text,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE UNIQUE INDEX `meal_plans_user_week_idx` ON `meal_plans` (`user_id`,`week_start_date`);",
      "CREATE TABLE `mood_entries` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`entry_id` text,\n\t`logged_at` text NOT NULL,\n\t`local_date` text NOT NULL,\n\t`mood` text,\n\t`energy` integer,\n\t`hunger` integer,\n\t`digestion` integer,\n\t`note` text,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`deleted_at` text,\n\t`synced_at` text,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`entry_id`) REFERENCES `journal_entries`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `mood_entries_user_date_idx` ON `mood_entries` (`user_id`,`local_date`);",
      "CREATE TABLE `pantry_items` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`food_item_id` text,\n\t`name` text NOT NULL,\n\t`quantity_grams` real,\n\t`added_at` text NOT NULL,\n\t`expires_on` text,\n\t`location` text DEFAULT 'pantry' NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`deleted_at` text,\n\t`synced_at` text,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`food_item_id`) REFERENCES `food_items`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `pantry_items_user_idx` ON `pantry_items` (`user_id`);",
      "CREATE TABLE `recipe_ingredients` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`recipe_id` text NOT NULL,\n\t`food_item_id` text,\n\t`name` text NOT NULL,\n\t`grams` real NOT NULL,\n\t`display_quantity` text NOT NULL,\n\t`preparation` text,\n\t`optional` integer DEFAULT false NOT NULL,\n\t`sort_order` integer DEFAULT 0 NOT NULL,\n\tFOREIGN KEY (`recipe_id`) REFERENCES `recipes`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`food_item_id`) REFERENCES `food_items`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `recipe_ingredients_recipe_idx` ON `recipe_ingredients` (`recipe_id`);",
      "CREATE TABLE `recipe_interactions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`recipe_id` text NOT NULL,\n\t`kind` text NOT NULL,\n\t`occurred_at` text NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`deleted_at` text,\n\t`synced_at` text,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`recipe_id`) REFERENCES `recipes`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `recipe_interactions_user_idx` ON `recipe_interactions` (`user_id`,`recipe_id`);",
      "CREATE TABLE `recipe_steps` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`recipe_id` text NOT NULL,\n\t`step_order` integer NOT NULL,\n\t`instruction` text NOT NULL,\n\t`duration_minutes` integer,\n\t`is_passive` integer DEFAULT false NOT NULL,\n\tFOREIGN KEY (`recipe_id`) REFERENCES `recipes`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `recipe_steps_recipe_idx` ON `recipe_steps` (`recipe_id`);",
      "CREATE TABLE `recipes` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`title` text NOT NULL,\n\t`summary` text NOT NULL,\n\t`cuisine` text NOT NULL,\n\t`meal_slots` text NOT NULL,\n\t`servings` integer NOT NULL,\n\t`prep_minutes` integer NOT NULL,\n\t`cook_minutes` integer NOT NULL,\n\t`difficulty` text NOT NULL,\n\t`equipment` text NOT NULL,\n\t`diet_styles` text NOT NULL,\n\t`allergens` text NOT NULL,\n\t`nutrients` text NOT NULL,\n\t`energy_kcal` real,\n\t`protein_g` real,\n\t`carbs_g` real,\n\t`fat_g` real,\n\t`fiber_g` real,\n\t`sugar_g` real,\n\t`sat_fat_g` real,\n\t`sodium_mg` real,\n\t`storage_notes` text,\n\t`fridge_days` integer DEFAULT 0 NOT NULL,\n\t`freezer_months` integer DEFAULT 0 NOT NULL,\n\t`prep_score` integer DEFAULT 0 NOT NULL,\n\t`estimated_cost_minor` integer,\n\t`review_state` text DEFAULT 'ai_generated' NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`deleted_at` text,\n\t`synced_at` text\n);",
      "CREATE INDEX `recipes_cuisine_idx` ON `recipes` (`cuisine`);",
      "CREATE INDEX `recipes_prep_score_idx` ON `recipes` (`prep_score`);",
      "CREATE TABLE `sync_outbox` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`table_name` text NOT NULL,\n\t`row_id` text NOT NULL,\n\t`operation` text NOT NULL,\n\t`payload` text NOT NULL,\n\t`queued_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`attempts` integer DEFAULT 0 NOT NULL,\n\t`last_error` text\n);",
      "CREATE INDEX `sync_outbox_queued_idx` ON `sync_outbox` (`queued_at`);",
      "CREATE TABLE `sync_state` (\n\t`table_name` text PRIMARY KEY NOT NULL,\n\t`last_pulled_at` text\n);",
      "CREATE TABLE `user_goals` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`effective_from` text NOT NULL,\n\t`goal` text NOT NULL,\n\t`diet_style` text DEFAULT 'balanced' NOT NULL,\n\t`rate_kg_per_week` real DEFAULT 0 NOT NULL,\n\t`energy_kcal` real NOT NULL,\n\t`protein_g` real NOT NULL,\n\t`carbs_g` real NOT NULL,\n\t`fat_g` real NOT NULL,\n\t`fiber_g` real NOT NULL,\n\t`estimated_expenditure_kcal` real,\n\t`estimate_confidence` text,\n\t`reason` text,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`deleted_at` text,\n\t`synced_at` text,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `user_goals_user_from_idx` ON `user_goals` (`user_id`,`effective_from`);",
      "CREATE TABLE `users` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`email` text,\n\t`display_name` text,\n\t`sex` text DEFAULT 'unspecified' NOT NULL,\n\t`birth_date` text,\n\t`height_cm` real,\n\t`activity_level` text DEFAULT 'moderate' NOT NULL,\n\t`cooking_skill` text DEFAULT 'comfortable' NOT NULL,\n\t`allergens` text DEFAULT '[]' NOT NULL,\n\t`disliked_ingredients` text DEFAULT '[]' NOT NULL,\n\t`equipment` text DEFAULT '[]' NOT NULL,\n\t`weekly_budget_minor` integer,\n\t`currency` text DEFAULT 'EUR' NOT NULL,\n\t`max_prep_minutes` integer DEFAULT 45 NOT NULL,\n\t`detailed_nutrition` integer DEFAULT false NOT NULL,\n\t`timezone` text DEFAULT 'UTC' NOT NULL,\n\t`onboarded_at` text,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`deleted_at` text,\n\t`synced_at` text\n);",
      "CREATE TABLE `water_logs` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`logged_at` text NOT NULL,\n\t`local_date` text NOT NULL,\n\t`millilitres` real NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`deleted_at` text,\n\t`synced_at` text,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `water_logs_user_date_idx` ON `water_logs` (`user_id`,`local_date`);",
      "CREATE TABLE `weight_entries` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`local_date` text NOT NULL,\n\t`weight_kg` real NOT NULL,\n\t`source` text DEFAULT 'manual' NOT NULL,\n\t`body_fat_percent` real,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`deleted_at` text,\n\t`synced_at` text,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE UNIQUE INDEX `weight_entries_user_date_idx` ON `weight_entries` (`user_id`,`local_date`);"
    ]
  },
  {
    "name": "0001_lyrical_mandroid.sql",
    "statements": [
      "CREATE TABLE `saved_meal_items` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`saved_meal_id` text NOT NULL,\n\t`food_item_id` text,\n\t`display_name` text NOT NULL,\n\t`grams` real NOT NULL,\n\t`portion_label` text,\n\t`nutrients` text NOT NULL,\n\t`confidence` real DEFAULT 1 NOT NULL,\n\t`source` text NOT NULL,\n\t`sort_order` integer DEFAULT 0 NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`deleted_at` text,\n\t`synced_at` text,\n\tFOREIGN KEY (`saved_meal_id`) REFERENCES `saved_meals`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`food_item_id`) REFERENCES `food_items`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `saved_meal_items_meal_idx` ON `saved_meal_items` (`saved_meal_id`);",
      "CREATE TABLE `saved_meals` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`meal_slot` text,\n\t`use_count` integer DEFAULT 0 NOT NULL,\n\t`last_used_at` text,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`deleted_at` text,\n\t`synced_at` text,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `saved_meals_user_idx` ON `saved_meals` (`user_id`);"
    ]
  },
  {
    "name": "0002_sad_cerebro.sql",
    "statements": [
      "CREATE TABLE `shopping_list_checks` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`item_key` text NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`deleted_at` text,\n\t`synced_at` text,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `shopping_list_checks_user_idx` ON `shopping_list_checks` (`user_id`,`item_key`);",
      "CREATE TABLE `shopping_list_recipes` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`recipe_id` text NOT NULL,\n\t`servings` integer NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`deleted_at` text,\n\t`synced_at` text,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`recipe_id`) REFERENCES `recipes`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `shopping_list_recipes_user_idx` ON `shopping_list_recipes` (`user_id`);"
    ]
  }
];
