/**
 * Generated by scripts/build-recipe-seed.mjs — do not edit.
 *
 * How many recipes `seed-recipes.generated.ts` holds. Kept separate so the
 * boot path can check whether seeding is needed without evaluating 496
 * recipe objects to find out.
 */

export const SEED_RECIPE_COUNT = 496;
