#!/usr/bin/env node
/**
 * Generate a photo for each dish from docs/image-prompts.jsonl.
 *
 *   node --env-file-if-exists=../../.env scripts/generate-images.mjs --model <id> --limit 2
 *   node --env-file-if-exists=../../.env scripts/generate-images.mjs --model <id>
 *
 * Resumable: a dish whose file already exists is skipped, so an interrupted run
 * costs nothing to restart and a single bad image can be regenerated by deleting
 * just that file. There are 170 dishes and every call is billed, so `--limit`
 * defaults to a small number — you have to ask for the full run explicitly.
 *
 * Failures never stop the run. They are collected and written to
 * `assets/dish-photos/failures.json` so a second pass can retry only those.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '..', '..', '..');

const { values } = parseArgs({
  options: {
    model: { type: 'string' },
    limit: { type: 'string' },
    size: { type: 'string', default: '1024x1024' },
    out: { type: 'string', default: 'assets/dish-photos' },
    concurrency: { type: 'string', default: '3' },
    only: { type: 'string' },
    retry: { type: 'boolean', default: false },
    'dry-run': { type: 'boolean', default: false },
  },
});

const BASE = process.env.YUNWU_BASE_URL ?? 'https://yunwu.ai/v1';
const KEY = process.env.YUNWU_API_KEY;
const MODEL = values.model;
const OUT = join(repoRoot, values.out);
const CONCURRENCY = Number(values.concurrency);

if (!KEY) {
  console.error('YUNWU_API_KEY is not set. Add it to .env at the repo root.');
  process.exit(1);
}
if (!MODEL) {
  console.error('--model is required. Run scripts/yunwu-models.mjs to see what your key can reach.');
  process.exit(1);
}

const slug = (title) =>
  title.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

let rows = readFileSync(join(repoRoot, 'docs', 'image-prompts.jsonl'), 'utf8')
  .trim().split('\n').map((l) => JSON.parse(l));

if (values.only) {
  const needle = values.only.toLowerCase();
  rows = rows.filter((r) => r.title.toLowerCase().includes(needle));
}

if (values.retry) {
  const path = join(OUT, 'failures.json');
  if (!existsSync(path)) {
    console.error('No failures.json to retry.');
    process.exit(1);
  }
  const failed = new Set(JSON.parse(readFileSync(path, 'utf8')).map((f) => f.title));
  rows = rows.filter((r) => failed.has(r.title));
}

mkdirSync(OUT, { recursive: true });
const pending = rows.filter((r) => !existsSync(join(OUT, `${slug(r.title)}.png`)));
const done = rows.length - pending.length;

const limit = values.limit ? Number(values.limit) : pending.length;
const batch = pending.slice(0, limit);

console.log(`${rows.length} dishes; ${done} already have a photo; ${pending.length} to go.`);
console.log(`This run: ${batch.length}  (model ${MODEL}, ${values.size}, ${CONCURRENCY} at a time)`);
if (values.limit === undefined && batch.length > 20) {
  console.log('\nNo --limit given, so this is the full run and every image is billed.');
}
if (values['dry-run']) {
  for (const r of batch) console.log(`  would generate ${slug(r.title)}.png  — ${r.title}`);
  process.exit(0);
}

async function generate(row) {
  const res = await fetch(`${BASE}/images/generations`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${KEY}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ model: MODEL, prompt: row.prompt, n: 1, size: values.size }),
  });

  if (!res.ok) throw new Error(`${res.status} ${res.statusText}: ${(await res.text()).slice(0, 300)}`);

  const body = await res.json();
  const item = body.data?.[0];
  if (!item) throw new Error(`no image in response: ${JSON.stringify(body).slice(0, 300)}`);

  // Models differ: some return base64 inline, some return a URL to fetch.
  if (item.b64_json) return Buffer.from(item.b64_json, 'base64');
  if (item.url) {
    const img = await fetch(item.url);
    if (!img.ok) throw new Error(`fetching returned url: ${img.status}`);
    return Buffer.from(await img.arrayBuffer());
  }
  throw new Error(`unrecognised response shape: ${Object.keys(item).join(', ')}`);
}

const failures = [];
let ok = 0;
let n = 0;

async function worker(queue) {
  for (;;) {
    const row = queue.shift();
    if (!row) return;
    const i = ++n;
    try {
      const buf = await generate(row);
      writeFileSync(join(OUT, `${slug(row.title)}.png`), buf);
      ok += 1;
      console.log(`  [${i}/${batch.length}] ${row.title} → ${slug(row.title)}.png (${Math.round(buf.length / 1024)} KB)`);
    } catch (error) {
      failures.push({ title: row.title, error: String(error.message ?? error) });
      console.log(`  [${i}/${batch.length}] ${row.title} — FAILED: ${String(error.message ?? error).slice(0, 120)}`);
    }
  }
}

const queue = [...batch];
await Promise.all(Array.from({ length: Math.min(CONCURRENCY, queue.length) }, () => worker(queue)));

writeFileSync(join(OUT, 'failures.json'), `${JSON.stringify(failures, null, 2)}\n`);

console.log(`\n${ok} generated, ${failures.length} failed.`);
console.log(`${readdirSync(OUT).filter((f) => f.endsWith('.png')).length} photos now in ${values.out}/`);
if (failures.length) console.log('Retry just those with:  --retry');
